### ISSUE TITLE
Please update bundled vulnerable Expat 2.2.1 to latest release >=2.4.3

### ISSUE THREAD

**Issue by hartwork** [the-real-blackh/hexpat#11]
Hi!

I noticed today that the bundle of Expat here is at version 2.2.1 still. There have been multiple security fixes after that so everyone using the bundled copy is at risk, with regard to the fixed vulnerabilities. Please check the [upstream change log](https://github.com/libexpat/libexpat/blob/a28238bdeebc087071777001245df1876a11f5ee/expat/Changes#L19) for more details. Thank you! :pray: 

Best, Sebastian

**Comment by hartwork** [comment]
Any thoughts?

**Comment by hartwork** [comment]
Any thoughts?

**Comment by hartwork** [comment]
Any news?

**Comment by kuribas** [comment]
Project is dead?

**Comment by hartwork** [comment]
Closing after one year to keep my https://github.com/issues page clean…
