### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by ndmitchell** [the-real-blackh/hexpat#3]
My experience is that hexpat is the fastest XML parsing library for Haskell. It would be nice if it was in Stackage.

**Comment by qrilka** [comment]
@ndmitchell I suppose now it's not the fastest? :)
And at the same time it's on Stackage - https://www.stackage.org/package/hexpat

**Comment by ndmitchell** [comment]
Indeed, no longer the fastest, but the fastest correct/robust one - glad to see it on stackahe
